### ISSUE TITLE
react-native link hangs 

### ISSUE THREAD

**Issue by Boredude** [dabit3/react-native-hackathon-starter#10]
the console is stuck after running _"react-native link"_ command

> Omri@OMRI-LAPTOP MINGW64 /c/Workspace/CrossPlatform/React-Native-Elements/react-native-hackathon-starter (master)
$ react-native link
rnpm-install info Linking react-native-vector-icons android dependency
rnpm-install info Android module react-native-vector-icons has been successfully linked
rnpm-install info iOS module react-native-vector-icons is already linked
rnpm-install info Linking assets to ios project
rnpm-install info Linking assets to android project
rnpm-install info Assets have been successfully linked to your project

Running on Windows 10

**Comment by SidMehta** [comment]
Hey @Boredude . Were you able to solve this issue?

**Comment by isnifer** [comment]
Hey, @Boredude did you solve this issue?
