### ISSUE TITLE
Failure while building JavaScript bundle

### ISSUE THREAD

**Issue by dakshshah96** [dabit3/react-native-hackathon-starter#100]
While trying to run the app by doing `npm start` after performing `npm install`, Expo fails to build the JavaScript bundle and I get the following error message:

```
Unable to resolve "react-native-screens" from "node_modules/react-navigation-stack/lib/module/views/StackView/StackViewCard.js"
```

Installing `react-native-screens` as a dependency by doing `expo install react-native-screens` seems to have fixed the issue.

**Comment by Monte9** [comment]
Good catch. I have pushed a new commit dc81f7cf53b6161ce3566c1c134f44874d8da047 that should fix it.
