### ISSUE TITLE
Fonts/Entypo.ttf not found.

### ISSUE THREAD

**Issue by glsgolden** [dabit3/react-native-hackathon-starter#103]
E:/Wokspace/REACTNATIVE_WORKSPACE/react-native-elements-app/src/helpers/vector-fonts.web.js
Module not found: Can't resolve '@expo/vector-icons/src/vendor/react-native-vector-icons/Fonts/Entypo.ttf' in 'E:\Wokspace\REACTNATIVE_WORKSPACE\react-native-elements-app\src\helpers'

**Comment by thegeekybaniya** [comment]
+1 same issue

**Comment by flyingcircle** [comment]
Check it out now.

**Comment by yangup** [comment]
same issue +1

**Comment by yangup** [comment]
![image](https://user-images.githubusercontent.com/28469164/87142268-e5a7f100-c2d6-11ea-8dfa-2272ceb3c07e.png)

change 'src' to 'build'

**Comment by flyingcircle** [comment]
@yangup please submit a PR
