### ISSUE TITLE
Button's onPress cannot call a lass as a function

### ISSUE THREAD

**Issue by itagakixt** [dabit3/react-native-hackathon-starter#13]
Hello,

I expect button will open another screen.

I create a test program to call another class using button's onPress.
But it failed with error(cannot call a lass as a function).

<Button
          small
          backgroundColor={socialColors.facebook}
          onPress={() => Home1()}
          title='Information'
          buttonStyle={styles.button} />

How can I call class Button's onPress?

Or class has to change to function?

Any suggestion will be appreciated.

Thanks,
Shoji

**Comment by itagakixt** [comment]
There are many code like this.

onPress={() => console.log('something')}

Is there any example not console but real class?

Thanks
Shoji

**Comment by Monte9** [comment]
@itagakixt Here's an example of a onPress that is not a console.log 
```javascript
onPressForgotPassword() {
  console.log("forgot password")
}

<Button
  small
  backgroundColor={socialColors.facebook}
  onPress={this.onPressForgotPassword}
  title='Information'
  buttonStyle={styles.button} />
```

Also, from what I understand, you are trying to navigate to another Class's view onPress right? For something like this, you might want to consider using a navigation library. Here's one you can check out: https://github.com/exponent/ex-navigation

**Comment by itagakixt** [comment]
Thanks for the reply and pointer!

I will check your pointer.

Thanks
