### ISSUE TITLE
Bug: No Landscape Mode support 

### ISSUE THREAD

**Issue by HariAcidReign** [dabit3/react-native-hackathon-starter#132]
Why is there no support for landscape mode? Is it intentional, or has it just not been implemented yet? 

**Behavior:**  On changing phone orientation, only the top status bar changes to the landscape. The entirety of the RNE app remains in portrait mode. 

If this is indeed a bug, I am willing to work on it immediately 🙌🏻

**Comment by flyingcircle** [comment]
Go for it

**Comment by HariAcidReign** [comment]
Gotcha! 🚀
