### ISSUE TITLE
Toggle switch Button on Settings page doesn't work

### ISSUE THREAD

**Issue by khushal87** [dabit3/react-native-hackathon-starter#135]
The toggle switch button on Settings page doesn't work. I can find a potential fix for it.

**Comment by khushal87** [comment]
Can I work on it?

**Comment by HariAcidReign** [comment]
@khushal87  Refer #120 
I don't think this issue fix is required for the same reason
(The main reason is that this is just a demo app and not meant to be fully functional)

**Comment by khushal87** [comment]
Okay, But if a user while testing the demo app can't interact with these events won't this be misleading? @HariAcidReign

**Comment by HariAcidReign** [comment]
Not necessarily, the app exists so that the developer can use these components in their own app, where they will add all the button functionalities that they need.

**Comment by khushal87** [comment]
Okay @pranshuchittora @Monte9 @flyingcircle @dabit3 Waiting for your review over the same and then I will close the issue if it is irrelevant.
