### ISSUE TITLE
Add new components support

### ISSUE THREAD

**Issue by khushal87** [dabit3/react-native-hackathon-starter#144]
There are some of the components which are officially there in the package but not shown in the application so I will to add the support for missing components and define views/add components for them. Thanks and hope this is not assigned to anyone.
Components/Views -

- [x] Checkbox
- [x] Tooltip
- [x] Overlay
- [x] Text Heading

**Comment by abhishekkumar08** [comment]
Could you please tell which component are you currently working on?

**Comment by khushal87** [comment]
Basically I have started with most of the components which are missing here, will create a PR tomorrow for the same.

**Comment by abhishekkumar08** [comment]
If you can be specific for the component, as I am also currently making the view of ```tooltip```, so no duplicates. Thanks.

**Comment by khushal87** [comment]
I am already done with tooltip and divider, would be picking up checkbox and others

**Comment by khushal87** [comment]
You can work on some other issues as I already have started with it.

**Comment by HariAcidReign** [comment]
Isn't `TextHeading` already in the app?

**Comment by khushal87** [comment]
There are 4 varieties of heading including h1, h2, h3, h4 which isn't shown up well on the app so I thought of making a new view for that. Although @flyingcircle I would appreciate your views over it. Thanks.

**Comment by Abhishek765** [comment]
@khushal87 can you tell me how you add a new component like I want to know the steps regarding that If I want to add a new component, can you tell me?

**Comment by khushal87** [comment]
In this app or in the package? @Abhishek765

**Comment by Abhishek765** [comment]
@khushal87  Like I guess you add in Package or so?

**Comment by Abhishek765** [comment]
And I think the user should be able to add in their application just like other components

**Comment by khushal87** [comment]
If you are talking about this issue, this actually deals with adding missing components from the main package to this app so that user can test them too.

**Comment by Abhishek765** [comment]
Btw did you add in Package or in this current project

**Comment by khushal87** [comment]
I am working on adding a new component in main package, for this project we can only add components which exist in main package.

**Comment by flyingcircle** [comment]
Yeah a view to show how the headings can be used can be helpful to people for sure.

**Comment by khushal87** [comment]
Okay, soon I will create a PR for the same
