### ISSUE TITLE
Lots of tsx warnings on String quotes

### ISSUE THREAD

**Issue by HariAcidReign** [dabit3/react-native-hackathon-starter#146]
All the strings in the codebase show a "Strings must use singlequote. eslintquotes" warning. 

They do not get cleared when I change the rules in `.eslintrc` to accommodate " as well

Looking for a solution and working on it, would love to get some pointers.

PS: This warning does not break the app, but it is a bit frustrating to see so many of these in the code

**Comment by flyingcircle** [comment]
Fixed in #156
