### ISSUE TITLE
Hide Tabs?

### ISSUE THREAD

**Issue by dustinromey** [dabit3/react-native-hackathon-starter#15]
I'm pushing a new route, and wondering how I might hide the Tab Bar in certain routes?

**Comment by Monte9** [comment]
@dustinromey `react-native-elements` uses [react-native-tab-navigator](https://github.com/exponent/react-native-tab-navigator). Check this [link](https://github.com/exponent/react-native-tab-navigator#hiding-the-tab-bar) to see how you can hide the tab bar using styles on the `Tab` component

Here's how I have implemented this in a couple of my projects. 

```
  hideTabBar(value) {
    this.setState({
      hideTabBar: value
    });
  }

  let tabBarStyle = {};
  let sceneStyle = {};
  if (this.state.hideTabBar) {
    tabBarStyle.height = 0;
    tabBarStyle.overflow = 'hidden';
    sceneStyle.paddingBottom = 0;
  }

<Tabs hidesTabTouch tabBarStyle={tabBarStyle} sceneStyle={sceneStyle}>
...
</Tab>
```

Also you can pass the func `hideTabBar` as a prop to other components and then hide the tab from from there as well like such:
```
<LoginView hideTabBar={this.hideTabBar.bind(this)} />

onLogout() {
    console.log("Logged out.");
    this.props.hideTabBar(true)
  }
```

**Comment by dustinromey** [comment]
Helpful, thanks!
