### ISSUE TITLE
UnMet Peer Dependency

### ISSUE THREAD

**Issue by TurtleWolfe** [dabit3/react-native-hackathon-starter#196]
While trying to install the demo, First time I got an `unmet peer dependency of React **16.3.1** needing to be updated to **17.0.1** and it suggested adding the `--legacy-peer-deps`
when I tried that I got a `corrupted hash sha`

![Screenshot from 2021-04-05 02-31-59](https://user-images.githubusercontent.com/7327259/113547410-d92d9c00-95bb-11eb-933f-9880f81ee706.png)
![Screenshot from 2021-04-05 02-58-15](https://user-images.githubusercontent.com/7327259/113547413-dc288c80-95bb-11eb-842b-a1b8ae2119b0.png)

**Comment by flyingcircle** [comment]
use `yarn`

**Comment by TurtleWolfe** [comment]
Is that really the only option and enough to close this over.. I hate yarn and use npm for everything

**Comment by TurtleWolfe** [comment]
I guess I'll try it for a demo, I'm just looking at the code samples.. still feels odd
