### ISSUE TITLE
Need to toggle sidemenu twice after closing.

### ISSUE THREAD

**Issue by izambasiron** [dabit3/react-native-hackathon-starter#21]
`isOpen` flag is not marked as false on closed.

Steps:
1. Launch app.
2. Open side menu by pressing hamburger icon.
3. Close side menu by tapping anywhere outside the sidemenu.
4. Press hambuger icon.

Expected result:
Sidemenu opens.

Actual result:
Sidemenu remain closed.

**Comment by Monte9** [comment]
Good catch! 

Thanks for the PR @izambasiron. It's been merged.
