### ISSUE TITLE
Stuttering when scrolling to bottom of About page on Android

### ISSUE THREAD

**Issue by izambasiron** [dabit3/react-native-hackathon-starter#24]
Platform:
Android

Steps:
1. Launch app on Android
2. Tap on About 
3. Scroll all the way to bottom

Expected result:
Scroll smoothly

Actual result:
Stutter at Half_Dome_from_Glacier_Point

**Comment by Monte9** [comment]
Good catch @izambasiron! 

PR #25 has been merged. Thanks.
