### ISSUE TITLE
Textfields don't receive focus on first load

### ISSUE THREAD

**Issue by iRoachie** [dabit3/react-native-hackathon-starter#33]
ref https://github.com/react-native-elements/react-native-elements/issues/829

**Comment by oxyii** [comment]
@iRoachie @Monte9 If textfields placed inside `ScrollView` please try to add [`keyboardShouldPersistTaps`](https://facebook.github.io/react-native/docs/scrollview#keyboardshouldpersisttaps) prop with `always` value if issue still actually.

**Comment by iRoachie** [comment]
Seems to be fixed now.
