### ISSUE TITLE
[Suggestions] Icons Library

### ISSUE THREAD

**Issue by louisiscoding** [dabit3/react-native-hackathon-starter#35]
Expo added a support for the Icon (https://docs.expo.io/versions/latest/guides/icons.html)

So you could use `@expo/vector-icons` instead of ` react-native-vector-icons`.
`@expo/vector-icons` is built on top of it so it has the same amount of icons and is compatible with Expo App.

Might be interesting to switch to  it 🌟

**Comment by Monte9** [comment]
@LouisJS great suggestion. Yes, using `@expo/vector-icons` over `react-native-vector-icons` for a expo app is the way to go. 

Feel free to submit a PR for this if you are interested. Should be fairly straight-forward.

**Comment by oxyii** [comment]
Excuse me but now you cannot use `react-native-vector-icons` inside expo app. All your includes RNVI [force redirects](https://github.com/expo/expo/blob/master/packages/babel-preset-expo/index.js#L15-L22) to `@expo/vector-icons` by default. But expo does not include native modules RNVI and some RNVI features is not worked in expo app. I mean `getImageSource`.
