### ISSUE TITLE
Getting a warning "Invalid prop `text` of type `object` supplied to `Button`, expected `string`"

### ISSUE THREAD

**Issue by oliverox** [dabit3/react-native-hackathon-starter#43]
This happens when trying to pass an `<Icon />` component as text in a `Button` component.
Buttons should be able to accept Icons as text. 

If I try to pass an `icon` property to `Button` without a `text` prop, the icon gets rendered to the left hand side of the button.

**Comment by Monte9** [comment]
This PR should fix the issue: https://github.com/react-native-training/react-native-elements-app/pull/41

**Comment by Monte9** [comment]
Should be fixed as the PR is merged. If this is an issue, lmk and I'll reopen it.
