### ISSUE TITLE
How to eject and run as native on device

### ISSUE THREAD

**Issue by montao** [dabit3/react-native-hackathon-starter#49]
Can I eject this project and create a native app that runs with native Android instead of expo?

Or is it only working with the expo?

Edit: I could run it as a native Android app with my Android device after (1) ejecting after adding eject script and (2) adding back node_modules by running npm install and then making a manual `gradlew assembleRelease` (3) deleted the Expo imports from the code (4) Changing the default script to App.js

Now I can run the thing with my physical Samsung S8 :-)

**Comment by xavier-villelegier** [comment]
Hey @montao, sorry for the delay. Yea you can eject but you'll need to remove the `Expo` usage in the project

**Comment by xavier-villelegier** [comment]
Closing this as inactive
