### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by SupriyaKalghatgi** [dabit3/react-native-hackathon-starter#5]
Unable to resolve module HSText from react-native-hackathon-starter/src/home/Home.js in its module map

**Comment by ajma** [comment]
I'm getting the same problem

**Comment by dabit3** [comment]
Sorry about that! I'm about to uplaod a new version. for now, `import { Text , ... }` from 'react-native-elements' and delete the other import. Thanks for bringing this to my attention.

**Comment by dabit3** [comment]
Just pushed up a new build and this is fixed! Thanks @ajma @SupriyaKalghatgi
