### ISSUE TITLE
Create a subview

### ISSUE THREAD

**Issue by montao** [dabit3/react-native-hackathon-starter#51]
If I want to create a "subview", say every person in the list from the list view should have a detailed view when the user is clicked, I could create such a view for elements in the list, but if I open the detailed view then there is not tabbed view and if I swipe left to right and open the drawer from the detailed view then I get an error message about no route for the view. 
```

Error: There is no route defined for key ButtonsTab.
Must be one of: 'Home','Lists_Detail','Details','navigationOptions'

This error is located at:
    in DrawerView (at DrawerNavigator.js:88)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at renderApplication.js:35)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
getScreenForRouteName
```

**Comment by montao** [comment]
Ok I found it in the project, it is "list_details" view and it works to include it. But I can't understand why it doesn't work to click the drawer back to the middle tab view from the profile or list or rating views. If I do that then the app crashes. I had to disable the drawernavigator from the middle tab(s) to avoid crashing states. This is not ideal. I want to learn how to use the drawernavigator combined with stacknavigator and tabnavigator but it is not well documented and difficult. If I don't disable the drawernavigator for the middle tab views then I get this error, difficult to understand:
```

Error: There is no route defined for key ButtonsTab.
Must be one of: 'Home','Lists_Detail'

This error is located at:
    in DrawerView (at DrawerNavigator.js:88)
    in Unknown (at createNavigator.js:13)
    in Navigator (at createNavigationContainer.js:226)
    in NavigationContainer (at renderApplication.js:35)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:102)
    in RCTView (at View.js:78)
    in View (at AppContainer.js:122)
    in AppContainer (at renderApplication.js:34)
getScreenForRouteName
```

**Comment by xavier-villelegier** [comment]
Closing this as it is not really related to this app but to React Navigation
