### ISSUE TITLE
Navigating using the DrawerNavigator

### ISSUE THREAD

**Issue by montao** [dabit3/react-native-hackathon-starter#52]
It's funny because if I navigate to the middle tab, then use the DrawerNavigator to navigate to the "profile" and then use the DrawerNavigator again to navigate to "components" then the app crashes with an error message about the routing.

**Comment by montao** [comment]
Ok I figured it out...how to make it work with no crash. The problems was the same with several different independent apps: "No route" when navigating between screens using the drawer. I did some changes to the navigation system and now it is stable. If you are interested I can share the changes or make a PR.

**Comment by Monte9** [comment]
@montao glad you figured it out. It would be awesome if you could submit a PR for it. 

Thanks in advance.
