### ISSUE TITLE
This project needs an update

### ISSUE THREAD

**Issue by gitowiec** [dabit3/react-native-hackathon-starter#62]
Expo says:
_This project uses Expo SDK v23.0.0. If you want to open this project, the author will need to update the project's SDK version._

I would like to view this library in Expo to decide if I want to use it.

**Comment by MinasG** [comment]
We can't access the demo, could you please escalate this update?

**Comment by Monte9** [comment]
@MinasG @gitowiec ah right. The app hasn't been updated in a while. Sorry about that.

But our team is aware of this and one of use will publish an updated version within the next few days. Stay tuned!

**Comment by zlwu** [comment]
Any updates on the new demo? Expo is too aggressive on version updates and it did not maintain a good compatibility to previous versions. It might be much better to detach from expo and go back to original react-native build scripts.

**Comment by shawnventi** [comment]
Any update on this?

**Comment by Monte9** [comment]
@iRoachie has updated the app and the new version has been published to expo!

Please try it out and let us know if you have any other questions.
