### ISSUE TITLE
Unable to resolve "react-navigation" from "App.js"

### ISSUE THREAD

**Issue by gbarnabic** [dabit3/react-native-hackathon-starter#72]
I get Unable to resolve "react-navigation" from "App.js" after a clean install.  If I install it via: npm install react-navigation I then get an error in the expo that says: Expo Developer Tools is disconnected from Expo CLI. Use the expo start command to start the CLI again. If I uninstall react-navigation the Expo error goes away but the app then shows the original unable to resolve error.  React npm expo all installed within the last few days and all the latest versions as far as I know.

**Comment by iRoachie** [comment]
I couldn't replicate this.

Here's the steps I took.

- Clone repo
- cd react-native-elements-app
- npm install
- npm start

Works as expected.

**Comment by zzAlexzz** [comment]
If you `npm install react-navigation`, you installed latest version which is 3.x. But this project is using version `1.5.8` which is out of date. You need to use their version to install this component:
- `yarn remove  react-navigation` (or `npm uninstall react-navigation`)
- add `react-navigation` with version `"react-navigation": "1.5.8"`
- `yarn` or `npm install`

I believe `react-navigation` need to be upgraded in `react-native-elements`..

**Comment by Monte9** [comment]
`react-navigation` has been updated to use `v3` thanks to @oxyii in [this PR](https://github.com/Monte9/react-native-elements-app/pull/74/commits/c93cfb29af08bd778754a2797edc9dc2c3d023aa).

Also, I have updated the readme with [up-to-date instructions](https://github.com/Monte9/react-native-elements-app#run-it-locally) on how to run the app locally & also on `web`. Hope this helps.
