### ISSUE TITLE
README proposal

### ISSUE THREAD

**Issue by oxyii** [dabit3/react-native-hackathon-starter#76]
@Monte9 My english is bad, so I'll not change readme )))

I think *Build* must be before deploy. Something like this:

### Build it

(...build instructions, `yarn build:ios`, ..., `yarn build:web` ...)

### Deploy it

after `yarn build:web` you can see generated `build` folder. This folder can be hosted as static website. For example you can publish on [Github Pages](https://pages.github.com/) via [gh-pages](https://github.com/tschaub/gh-pages) cli
```bash
gh-pages -d build
```
**Note** don't forget to add or change "homepage" key in your `package.json`

...

and bla-bla-bla ....

**Comment by Monte9** [comment]
haha this is related to #77. I just worked on the `gh-pages` deploy and ran into an issue.

Also I'll add the build step to the readme. I'll close this issue for now and let's coordinate this on #77

**Comment by Monte9** [comment]
Updated readme here: https://github.com/react-native-elements/react-native-elements-app#deploy-web-app
