### ISSUE TITLE
Error with expo 34.0.0

### ISSUE THREAD

**Issue by jgutierro** [dabit3/react-native-hackathon-starter#85]
Please provide an updated example of the demo app with the latest expo version 34.0.0. Actually with this version of demo app if you try to [upgrade expo](https://docs.expo.io/versions/latest/workflow/upgrading-expo-sdk-walkthrough/) There's a lot of errors.

**Comment by iRoachie** [comment]
Started the process on https://github.com/react-native-elements/react-native-elements-app/tree/update. Still having some issues with RNW.

**Comment by oxyii** [comment]
@iRoachie We must totally recreate app. It will not touch screen files and navigation but will upgrade all deps. eg `@babel/polyfill` already deprecated, `react-native-gesture-handler` can work fine without tricks like [this](https://github.com/react-native-elements/react-native-elements-app/pull/74#issuecomment-475649064) and more, and more, and more. I'm working on it now.

**Comment by iRoachie** [comment]
Ahh okay, lemme know if you need me to jump on anything

**Comment by oxyii** [comment]
@iRoachie

> Still having some issues with RNW.

Yep! This is a [lost fix](https://github.com/react-native-elements/react-native-elements-app/pull/74#issuecomment-470097579). I mean `React.forwardRef` in `PadView`

**Comment by iRoachie** [comment]
Exactly why doesn't that work though in rnw?

**Comment by oxyii** [comment]
I was able to run this app on web-platform after re-init on expo v34. Broken scrolls (I don't know why yet, will digging) and not working `Lists` tab because of forwardRef missing (see [facebook/react-native#1040](https://github.com/facebook/react-native/issues/1040))

**Comment by iRoachie** [comment]
Based on that thread should we just wrap the children of all touchable components in a View?

**Comment by oxyii** [comment]
I'm not sure... I know exactly about errors on web-platform exactly in PadView part of ListItem. I have never met this error anywhere else.

**Comment by oxyii** [comment]
Move this discussion to PR #87
