### ISSUE TITLE
react-native-elements issue

### ISSUE THREAD

**Issue by Ranjithkumartheegala** [dabit3/react-native-hackathon-starter#94]
Hi
I am cloning the same code of your git and import visual studio and install "npm install --save" then go to run "yarn start" it is running but it is showing below issue please solve this my problem Sir 

![Screenshot from 2019-11-15 12-25-26](https://user-images.githubusercontent.com/57788696/68923492-76f4b100-07a4-11ea-8c81-17f2b6d16650.png)

**Comment by iRoachie** [comment]
Cc @Monte9

**Comment by tberghuis** [comment]
rename file src/tabs/settings.js to src/tabs/Settings.js

**Comment by tingzhouu** [comment]
Can i help to update the file reference?

**Comment by iRoachie** [comment]
sure ting @tingzhouu

**Comment by Ranjithkumartheegala** [comment]
solved my problem

**Comment by YoLoveLife** [comment]
why not fix this problem.wwwwww
just allow pull request. thx

**Comment by iRoachie** [comment]
@YoLoveLife Merged
